// Manually generated

// #undef COMPILE_IN_DEFAULT_FONT
// #undef DEBUG_THREADS
#define DEFAULT_PATHSEP ":"
// #undef DO_COLLISION_RECORDING
// #undef DO_MEMORY_USAGE
// #undef DO_PIPELINING
// #undef DO_PSTATS
// #undef EXPORT_TEMPLATES
// #undef GETTIMEOFDAY_ONE_PARAM
// #undef GLOBAL_ARGC
// #undef GLOBAL_ARGV
// #undef GLOBAL_OPERATOR_NEW_EXCEPTIONS
// #undef HAVE_ARTOOLKIT
#define HAVE_AUDIO 1
// #undef HAVE_BMP
// #undef HAVE_CG
// #undef HAVE_CGDX9
// #undef HAVE_CGGL
// #undef HAVE_CHROMIUM
// #undef HAVE_DINKUM
// #undef HAVE_DIRECTCAM
// #undef HAVE_DX8
// #undef HAVE_DX9
// #undef HAVE_EGG
// #undef HAVE_EGL
// #undef HAVE_FCOLLADA
// #undef HAVE_FFMPEG
#define HAVE_FFTW 1
// #undef HAVE_FMODEX
#define HAVE_FREETYPE 1
#define HAVE_GETOPT 1
// #undef HAVE_GETOPT_LONG_ONLY
#define HAVE_GETTIMEOFDAY 1
// #undef HAVE_GL
#define HAVE_GLES 1
// #undef HAVE_GLES2
// #undef HAVE_GLOBAL_ARGV
// #undef HAVE_GLX
// #undef HAVE_IMG
#define HAVE_IOS_BINARY 1
#define HAVE_IOS_TYPEDEFS 1
#define HAVE_JPEG 1
// #undef HAVE_MAYA
// #undef HAVE_MESA
#define HAVE_NAMESPACE 1
#define HAVE_NET 1
// #undef HAVE_NVIDIACG
#define HAVE_ODE 1
// #undef HAVE_OPENAL
// #undef HAVE_OPENAL_FRAMEWORK
// #undef HAVE_OPENCV
// #undef HAVE_OPENSSL
// #undef HAVE_OPEN_MASK
// #undef HAVE_P3D_PLUGIN
#define HAVE_PNG 1
#define HAVE_PNM 1
// #undef HAVE_POSIX_THREADS
// #undef HAVE_PROC_CURPROC_FILE
// #undef HAVE_PROC_CURPROC_MAP
// #undef HAVE_PROC_SELF_CMDLINE
// #undef HAVE_PROC_SELF_CMDLINE
// #undef HAVE_PROC_SELF_ENVIRON
// #undef HAVE_PROC_SELF_EXE
// #undef HAVE_PROC_SELF_MAPS
#define HAVE_PYTHON 1
#define HAVE_RTTI 1
// #undef HAVE_SGIGL
#define HAVE_SGI_RGB 1
// #undef HAVE_SOFTIMAGE
// #undef HAVE_SOFTIMAGE_PIC
// #undef HAVE_SQUISH
// #undef HAVE_STL_HASH
#define HAVE_STREAMSIZE 1
// #undef HAVE_SWSCALE
// #undef HAVE_TGA
// #undef HAVE_THREADS
// #undef HAVE_TIFF
#define HAVE_TYPENAME 1
// #undef HAVE_VIDEO4LINUX
// #undef HAVE_VRPN
#define HAVE_WCHAR_T 1
// #undef HAVE_WGL
#define HAVE_WSTRING 1
// #undef HAVE_X11
// #undef HAVE_XCURSOR
// #undef HAVE_XF86DGA
// #undef HAVE_XRANDR
#define HAVE_ZLIB 1
// #undef IOCTL_TERMINAL_WIDTH
// #undef IS_FREEBSD
// #undef IS_LINUX
// #undef IS_OSX
// #undef LINK_IN_GL
// #undef LINK_IN_PHYSICS
// #undef MAYA_PRE_5_0
// #undef MESA_MGL
// #undef NOTIFY_DEBUG
#define OS_SIMPLE_THREADS 1
// #undef PHAVE_ALLOCA_H
#define PHAVE_DIRENT_H 1
#define PHAVE_GETOPT_H 1
// #undef PHAVE_GLOB_H
#define PHAVE_IOSTREAM 1
// #undef PHAVE_IO_H
#define PHAVE_JPEGINT_H 1
#define PHAVE_LIMITS_H 1
// #undef PHAVE_LINUX_INPUT_H
#define PHAVE_LOCALE_H 1
#define PHAVE_MALLOC_H 1
// #undef PHAVE_MINMAX_H
#define PHAVE_NEW 1
#define PHAVE_SSTREAM 1
#define PHAVE_STDINT_H 1
#define PHAVE_STDLIB_H 1
#define PHAVE_STRING_H 1
// #undef PHAVE_SYS_MALLOC_H
// #undef PHAVE_SYS_SOUNDCARD_H
#define PHAVE_SYS_TIME_H 1
#define PHAVE_SYS_TYPES_H 1
// #undef PHAVE_UCONTEXT_H
#define PHAVE_UNISTD_H 1
#define PHAVE_UTIME_H 1
#define PRC_SAVE_DESCRIPTIONS 1
// #undef PROTOTYPE_GLOBAL_ARGV
// #undef PYTHON_FRAMEWORK
// #undef REPORT_OPENSSL_ERRORS
// #undef SIMPLE_STRUCT_POINTERS
#define SIMPLE_THREADS 1
// #undef SSL_097
// #undef STATIC_INIT_GETENV
// #undef SUPPORT_IMMEDIATE_MODE
// #undef TRACK_IN_INTERPRETER
// #undef USE_DEBUG_PYTHON
// #undef USE_DELETED_CHAIN
// #undef USE_MEMORY_DLMALLOC
#define USE_MEMORY_MALLOC 1
// #undef USE_MEMORY_PTMALLOC
#define USE_PANDAFILESTREAM 1
#define USE_STL_ALLOCATOR 1
// #undef WORDS_BIGENDIAN
// #undef _SECURE_SCL
// #undef _SECURE_SCL_THROWS

#define DTOOL_PLATFORM "switch"